name: 'Karate testing'
description: 'Run Karate tests'
author: 'Erik Bos'
inputs:
  url:
    description: "URL to pass as script variable to test."
    required: false
  tests:
    description: 'Karata file or directory path with tests.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Docker
      run: |
        docker build -t local-karate .
      shell: bash

    - name: Run Docker container on host network
      run: |
        docker run --network host local-karate ${{ inputs.tests }} ${{ inputs.url }}
      shell: bash
